<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DspApplication;
use Illuminate\Support\Str;

class DspApplicationSeeder extends Seeder
{
    public function run(): void
    {
        $apps = [
            [
                'application_number'               => 'DSP-2026-NASHIK1',
                'application_date'                 => now()->subDays(2)->toDateString(),
                'preferred_territory_area'         => 'Nashik City & Panchavati',
                'pincodes'                         => '422001, 422002, 422003',
                'district'                         => 'Nashik',
                'state'                            => 'Maharashtra',
                'applicant_name'                   => 'Rajesh Shantaram Patil',
                'father_or_spouse_name'            => 'Shantaram Patil',
                'date_of_birth'                    => '1985-06-15',
                'mobile'                           => '9822012345',
                'password'                         => \Illuminate\Support\Facades\Hash::make('password123'),
                'whatsapp'                         => '9822012345',
                'email'                            => 'rajesh.patil@nashikservices.com',
                'residential_address'              => 'Plot 45, Anand Nagar, Gangapur Road, Nashik',
                'residential_pincode'              => '422005',
                'business_name'                    => 'Patil Motors & Electronic Services',
                'business_constitution'            => 'proprietorship',
                'year_established'                 => '2016',
                'pan'                              => 'AABCP1234F',
                'gstin'                            => '27AABCP1234F1Z5',
                'existing_business_activity'       => 'Two-wheeler service & Home appliance dealership',
                'years_of_experience'              => '8',
                'premises_type'                    => 'owned',
                'complete_address'                 => 'Gala No 1-4, Patil Commercial Complex, Dwarka Circle, Nashik',
                'premises_pincode'                 => '422001',
                'total_area_sqft'                  => 1850.00,
                'frontage_feet'                    => 35.00,
                'available_facilities'             => ['product_storage', 'cctv', 'customer_reception', 'fire_safety', 'service_workshop', 'secure_storage', 'electricity', 'internet', 'parking'],
                'presently_operate_service_centre' => true,
                'technicians_count'                => 4,
                'ev_technician_status'             => 'yes',
                'electrical_technician_status'     => 'yes',
                'home_appliance_technician_status' => 'yes',
                'agree_to_nexvia_training'         => true,
                'products_handled'                 => ['electric_scooters', 'smart_tvs', 'refrigerators', 'washing_machines', 'air_conditioners', 'all_approved'],
                'vehicles_two_wheeler'             => 3,
                'vehicles_three_wheeler'           => 1,
                'vehicles_pickup_lcv'              => 2,
                'vehicles_other'                   => '1 Bolero Camper',
                'max_delivery_radius_km'           => 40.00,
                'pdi_handover_sop'                 => true,
                'otp_delivery_confirmation'        => true,
                'security_deposit_amount'          => 1000000.00,
                'deposit_terms_agreed'             => true,
                'deposit_payment_status'           => 'paid',
                'deposit_transaction_reference'    => 'IDFB26091877492',
                'declaration_agreed'               => true,
                'declaration_date'                 => now()->subDays(2)->toDateString(),
                'declaration_signature_name'       => 'Rajesh Shantaram Patil',
                'status'                           => 'approved',
                'wallet_balance'                   => 3500.00,
                'total_earned'                     => 3500.00,
                'total_redeemed'                   => 0.00,
                'payout_account_number'            => '10048728156',
                'payout_ifsc'                      => 'IDFB0042281',
                'payout_bank_name'                 => 'IDFC FIRST Bank',
                'payout_holder_name'               => 'Rajesh Shantaram Patil',
                'payout_upi_id'                    => 'rajeshpatil@idfcbank',
                'admin_notes'                      => 'Initial KYC and workshop photos verified. Approved for Nashik territory.',
            ],
            [
                'application_number'               => 'DSP-2026-PUNE02',
                'application_date'                 => now()->subDays(5)->toDateString(),
                'preferred_territory_area'         => 'Pune Hadapsar & Kharadi',
                'pincodes'                         => '411028, 411014',
                'district'                         => 'Pune',
                'state'                            => 'Maharashtra',
                'applicant_name'                   => 'Suresh Dattatray Kadam',
                'father_or_spouse_name'            => 'Dattatray Kadam',
                'date_of_birth'                    => '1990-11-20',
                'mobile'                           => '9922554433',
                'password'                         => \Illuminate\Support\Facades\Hash::make('password123'),
                'whatsapp'                         => '9922554433',
                'email'                            => 'suresh.kadam@kadamlogistics.in',
                'residential_address'              => 'Flat 302, Green Valley, Magarpatta, Pune',
                'residential_pincode'              => '411028',
                'business_name'                    => 'Kadam Express Delivery & Tech Services LLP',
                'business_constitution'            => 'llp',
                'year_established'                 => '2020',
                'pan'                              => 'AAAFK5678L',
                'gstin'                            => '27AAAFK5678L1Z2',
                'existing_business_activity'       => 'Logistics hub and electrical maintenance',
                'years_of_experience'              => '4',
                'premises_type'                    => 'leased',
                'complete_address'                 => 'Warehouse 12, Logistics Park, Pune-Solapur Highway, Hadapsar, Pune',
                'premises_pincode'                 => '411028',
                'total_area_sqft'                  => 2400.00,
                'frontage_feet'                    => 40.00,
                'available_facilities'             => ['product_storage', 'cctv', 'customer_reception', 'fire_safety', 'secure_storage', 'electricity', 'internet', 'parking'],
                'presently_operate_service_centre' => true,
                'technicians_count'                => 3,
                'ev_technician_status'             => 'will_recruit',
                'electrical_technician_status'     => 'yes',
                'home_appliance_technician_status' => 'yes',
                'agree_to_nexvia_training'         => true,
                'products_handled'                 => ['smart_tvs', 'refrigerators', 'washing_machines', 'air_conditioners', 'mixer_grinders', 'kitchen_chimneys'],
                'vehicles_two_wheeler'             => 4,
                'vehicles_three_wheeler'           => 2,
                'vehicles_pickup_lcv'              => 2,
                'max_delivery_radius_km'           => 35.00,
                'pdi_handover_sop'                 => true,
                'otp_delivery_confirmation'        => true,
                'security_deposit_amount'          => 1000000.00,
                'deposit_terms_agreed'             => true,
                'deposit_payment_status'           => 'verified',
                'deposit_transaction_reference'    => 'CMS9988221100',
                'declaration_agreed'               => true,
                'declaration_date'                 => now()->subDays(5)->toDateString(),
                'declaration_signature_name'       => 'Suresh Dattatray Kadam',
                'status'                           => 'approved',
                'wallet_balance'                   => 8750.00,
                'total_earned'                     => 8750.00,
                'total_redeemed'                   => 0.00,
                'payout_account_number'            => '919922554433',
                'payout_ifsc'                      => 'HDFC0000123',
                'payout_bank_name'                 => 'HDFC Bank',
                'payout_holder_name'               => 'Kadam Express Delivery & Tech Services LLP',
                'payout_upi_id'                    => 'sureshkadam@okhdfcbank',
                'admin_notes'                      => 'Approved by Operations Head. Deposit confirmed in IDFC bank account.',
            ],
        ];

        foreach ($apps as $appData) {
            DspApplication::updateOrCreate(
                ['application_number' => $appData['application_number']],
                $appData
            );
        }
    }
}
